CREATE TABLE IF NOT EXISTS users (
 id SERIAL PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL,
 password_hash TEXT NOT NULL, phone TEXT, location TEXT, role TEXT NOT NULL DEFAULT 'user',
 created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS listings (
 id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 title TEXT NOT NULL, description TEXT NOT NULL, price NUMERIC(14,2) NOT NULL,
 category TEXT NOT NULL, location TEXT NOT NULL, image_url TEXT,
 status TEXT NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS favorites (
 user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 listing_id INTEGER REFERENCES listings(id) ON DELETE CASCADE,
 PRIMARY KEY(user_id, listing_id)
);
CREATE TABLE IF NOT EXISTS messages (
 id SERIAL PRIMARY KEY, sender_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 receiver_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
 listing_id INTEGER REFERENCES listings(id) ON DELETE CASCADE,
 body TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW()
);
